Added gitmoji.dev keywords
muan/emojilib pull request #231
Opened 2024-10-16 10:15 UTC by BreakingTV

These keywords are just quickly thought out in my head. If you have any improvements or other requests for changes, feel free to review!

2024-10-16 10:16 UTC, BreakingTV commented
Closes: #230

2024-10-20 09:23 UTC, muan requested changes
Hi, could you uncheck the package-lock.json changes?

2024-10-20 11:49 UTC, BreakingTV commented
@muan done!

2024-10-20 11:55 UTC, BreakingTV commented
was a bit to fast... removed the entire package-lock...
but now it should be done! @muan

2024-10-22 10:39 UTC, muan submitted a review, later dismissed
Hey, I ended up having to generalize most of this. I am not sure what your use case for this library is, but this is not meant to be `:emoji_short_code:`. 

If you want to keep the specificity I'd suggest that you keep your own list and add on top of `emojilib`.

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "data_inspection"
```suggestion
    "exploration",
    "inspection"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "bad_code",
```suggestion
    "bad",
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "external_api",
```suggestion
    "external",
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "update_gitignore"
```suggestion
    "prohibited",
    "ignore"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "fix_ci_build"
```suggestion
    "nct"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "breaking_changes"
```suggestion
    "break"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "update_transitions",
```suggestion
    "animations",
    "transitions"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "update_literals"
```suggestion
    "text",
    "literals"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "improve_developer_experience"
```suggestion
    "developer"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "update_contributor"
```suggestion
    "contributors"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "update_seed_files"
```suggestion
    "seed"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "add_easter_egg"
```suggestion
    "easter_egg"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "update_assets"
```suggestion
    "assets"
```

a bit far fetched but eh.

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "write_drunkenly"
```suggestion
    "mug"
```

drunk is already a keyword.

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "architectural_changes"
```suggestion
    "architectural"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "infrastructure_changes"
```suggestion
    "infrastructure"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "hotfix"
```suggestion
    "vehicle"
```

Sorry I don't think this is general enough.

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "rename_resources"
```suggestion
    "vehicle",
    "resources"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "fix_linter_warning"
```suggestion
    "vehicle",
    "warning"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "improve_performance"
```suggestion
    "thunderbolt",
    "speed"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "new_feature"
```suggestion
    "star"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "begin_project"
```suggestion
    "hooray"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "catch_errors"
```suggestion
    "sports",
    "catch"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "improve_format"
```suggestion
    "improve"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "update_concurrency"
```suggestion
    "crafts"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "upgrade_dependencies"
```suggestion
    "upgrade"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "downgrade_dependencies"
```suggestion
    "downgrade"
```

2024-10-22 10:39 UTC, muan commented on dist/emoji-en-US.json
> +    "remove_dependency"
```suggestion
    "remove"
```

2024-10-23 11:18 UTC, BreakingTV commented
Completly fine with these suggestions ^^
My bad for not generalizing them, but I think this way its even better!

2024-10-30 13:18 UTC, muan commented
Thanks. I'll probably take another pass before publishing. I'll let you know when it's released.

2024-10-30 13:18 UTC, merged